'use strict'; // code generated by pbf v3.1.0

// PlaybackPacket ========================================

var PlaybackPacket = exports.PlaybackPacket = {};

PlaybackPacket.read = function (pbf, end) {
    return pbf.readFields(PlaybackPacket._readField, {session_id: 0, channel_id: 0, timestamp_delta: 0, payload: null}, end);
};
PlaybackPacket._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.session_id = pbf.readVarint();
    else if (tag === 2) obj.channel_id = pbf.readVarint();
    else if (tag === 3) obj.timestamp_delta = pbf.readSVarint();
    else if (tag === 4) obj.payload = pbf.readBytes();
};
PlaybackPacket.write = function (obj, pbf) {
    if (obj.session_id) pbf.writeVarintField(1, obj.session_id);
    if (obj.channel_id) pbf.writeVarintField(2, obj.channel_id);
    if (obj.timestamp_delta) pbf.writeSVarintField(3, obj.timestamp_delta);
    if (obj.payload) pbf.writeBytesField(4, obj.payload);
};
