'use strict'; // code generated by pbf v3.1.0

var PacketType = exports.PacketType = {
    "PING": 1,
    "HELLO": 100,
    "PING_CAMERA": 101,
    "AUDIO_PAYLOAD": 102,
    "START_PLAYBACK": 103,
    "STOP_PLAYBACK": 104,
    "CLOCK_SYNC_ECHO": 105,
    "LATENCY_MEASURE": 106,
    "TALKBACK_LATENCY": 107,
    "METADATA_REQUEST": 108,
    "OK": 200,
    "ERROR": 201,
    "PLAYBACK_BEGIN": 202,
    "PLAYBACK_END": 203,
    "PLAYBACK_PACKET": 204,
    "LONG_PLAYBACK_PACKET": 205,
    "CLOCK_SYNC": 206,
    "REDIRECT": 207,
    "TALKBACK_BEGIN": 208,
    "TALKBACK_END": 209,
    "METADATA": 210,
    "METADATA_ERROR": 211,
    "AUTHORIZE_REQUEST": 212
};

// PlaybackPacket ========================================

var PlaybackPacket = exports.PlaybackPacket = {};

PlaybackPacket.read = function (pbf, end) {
    return pbf.readFields(PlaybackPacket._readField, {session_id: 0, channel_id: 0, timestamp_delta: 0, payload: null}, end);
};
PlaybackPacket._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.session_id = pbf.readVarint();
    else if (tag === 2) obj.channel_id = pbf.readVarint();
    else if (tag === 3) obj.timestamp_delta = pbf.readSVarint();
    else if (tag === 4) obj.payload = pbf.readBytes();
};
PlaybackPacket.write = function (obj, pbf) {
    if (obj.session_id) pbf.writeVarintField(1, obj.session_id);
    if (obj.channel_id) pbf.writeVarintField(2, obj.channel_id);
    if (obj.timestamp_delta) pbf.writeSVarintField(3, obj.timestamp_delta);
    if (obj.payload) pbf.writeBytesField(4, obj.payload);
};
