needs-questionnaire:
  comment: |
    Please fill out the questionnaire provided in the bug report template.

    ```
    On what OS are you running homebridge: 
    On what iOS version are you having issues: 
    What camera types are having issues: 
    Does this issue occur consistently or randomly: 
    If applicable, what was the last version that worked properly: 
    ```

  labels:
    - needs-questionnaire
