name: issueCheck
# This workflow is triggered when a label is added to an issue.
on:
  issues:
    types: labeled

jobs:
  processLabelAction:
    # if: "contains(github.event.issue.labels.*.name, 'bug') == 'true' && contains(github.event.issue.body, 'On what OS are you running homebridge') != 'true'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hramos/label-actions@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
