name: issueCheck
# This workflow is triggered when a label is added to an issue.
on:
  issues:
    types: labeled

jobs:
  processLabelAction:
    name: Process Label Action
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.issue.labels.*.name, 'bug') == 'true' && contains(github.event.issue.body, 'On what OS are you running homebridge') != 'true'
      - uses: actions/checkout@v2
      - name: Process Label Action
        uses: hramos/label-actions@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
